<?php
// var_dump($stockkeluar);exit();
?>

<head>
    <style type="text/css">
        /*body{
      padding-top:1000px;
      margin-top:1000px;
    }*/
        h4 {
            font-size: 14px;
        }

        table tr td {
            font-size: 10px;
        }

        .center {
            display: block;
            margin-left: auto;
            margin-right: auto;
            /*width: 50%;*/
        }

        .singleborder {
            border-collapse: collapse;
            border: 1px solid black;
        }

        body {
            font-size: 10px;
        }
    </style>
    <title>Bukti Keluar Barang</title>
</head>

<body>
    <table border="0" width="100%">
        <tr>
            <td rowspan="2" width="12%"><img width="10%" height="10%" src="./assets/qrcode/bkb/<?php echo $id . "_" . $no_bkb; ?>.png"></td>
            <td align="center" valign="bottom">
                <h4 align="center" style="margin: 0px;padding: 0px;">BUKTI KELUAR BARANG</h4>
            </td>
        </tr>
        <tr>
            <td align="center" valign="baseline">
                <h5 align="center" style="margin: 0px;padding: 0px 0px 10px 0px;"><b><?= $stockkeluar->NO_REF; ?></b></h5>
            </td>
        </tr>
    </table>
    <table width="100%">
        <tr>
            <td>Depart/Divisi : <?= $stockkeluar->bag; ?></td>
            <td align="right">No BPB : <?= $stockkeluar->nobpb; ?></td>
        </tr>
    </table>
    <table class="singleborder" border="1" width="100%">
        <tr>
            <td align="center" rowspan="2">No</td>
            <td align="center" rowspan="2">No. Kode Barang</td>
            <td align="center" rowspan="2">Nama / Spesifikasi Barang</td>
            <td align="center" rowspan="2">Sat</td>
            <td align="center" colspan="2">Jumlah</td>
            <td align="center" rowspan="2">Kode Beban</td>
            <td align="center" rowspan="2">Blok</td>
            <td align="center" rowspan="2">Keterangan</td>
        </tr>
        <tr>
            <td>Diminta</td>
            <td>Dikeluarkan</td>
        </tr>
        <?php
        $no = 1;
        foreach ($keluarbrgitem as $listkeluarbrgitem) {
            // var_dump($keluarbrgitem);exit();
        ?>
            <tr>
                <td><?= $no ?></td>
                <td><?= $listkeluarbrgitem->kodebartxt; ?></td>
                <td><?= $listkeluarbrgitem->nabar; ?></td>
                <td><?= $listkeluarbrgitem->satuan; ?></td>
                <td><?= $listkeluarbrgitem->qty; ?></td>
                <td><?= $listkeluarbrgitem->qty2; ?></td>
                <td><?= $listkeluarbrgitem->kodebebantxt; ?></td>
                <td><?= $listkeluarbrgitem->blok; ?></td>
                <td><?= $listkeluarbrgitem->ket; ?></td>
            </tr>
        <?php } ?>
        <tr>
            <td colspan="2">
                Distribusi :<br />
                -Ke 1 - Kantor Kebun/PKS<br />
                -Ke 2 - Gudang
            </td>
            <td colspan="7">
                <table border="0" width="100%">
                    <tr>
                        <td align="center">Dibukukan,</td>
                        <td align="center">Diperiksa,</td>
                        <td align="center">Dibuat oleh,</td>
                        <td align="center">DIterima oleh,</td>
                        <td align="center">Tanggal</td>
                    </tr>
                    <tr>
                        <td colspan="4" height="50"></td>
                        <td align="center" valign="top" rowspan="3"> <?= date("d-m-Y", strtotime($stockkeluar->tgl)); ?></td>
                    </tr>
                    <tr>
                        <td align="center">(___________________)</td>
                        <td align="center">(___________________)</td>
                        <td align="center">(___________________)</td>
                        <td align="center">(___________________)</td>
                    </tr>
                    <tr>
                        <td align="center">Kasie Pembukuan</td>
                        <td align="center">KTU</td>
                        <td align="center">Kasie Gudang</td>
                        <td align="center"></td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
    <small><i>Tgl Cetak <?= date("d/m/Y H:i:s"); ?> - Client <?= $this->input->ip_address(); ?> <?= $this->platform->agent(); ?></i></small><br />
    <small><i>Cetakan ke - <?= $urut['cetak'] ?></i></small><br>
    <small>Print generated by MMOP Website</small>
</body>